    export const booksData = [
        {
            id: 1,
            title: 'The Art of Learning',
            author: 'Josh Waitzkin',
            category: 'education',
            price: 2500,
            oldPrice: 5000,
            discount: '-50%',
            rating: 4.5,
            reviews: 124,
            format: 'PDF',
            pages: 256,
            image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=500&fit=crop',
            description: 'A comprehensive guide to mastering the art of learning and skill development. Learn the secrets of peak performance.',
        },
        {
            id: 2,
            title: 'Digital Marketing Mastery',
            author: 'Sarah Johnson',
            category: 'business',
            price: 3200,
            oldPrice: 6500,
            discount: '-51%',
            rating: 4.8,
            reviews: 89,
            format: 'PDF',
            pages: 342,
            image: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&h=500&fit=crop',
            description: 'Master digital marketing strategies and grow your online presence. Complete guide to modern marketing.',
        },
        {
            id: 3,
            title: 'Python Programming Guide',
            author: 'Michael Chen',
            category: 'technology',
            price: 2800,
            oldPrice: 5500,
            discount: '-49%',
            rating: 4.7,
            reviews: 156,
            format: 'PDF',
            pages: 428,
            image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=500&fit=crop',
            description: 'Complete Python programming guide from basics to advanced concepts. Perfect for beginners and professionals.',
        },
        {
            id: 4,
            title: 'Business Strategy Essentials',
            author: 'David Miller',
            category: 'business',
            price: 3500,
            oldPrice: 7000,
            discount: '-50%',
            rating: 4.6,
            reviews: 92,
            format: 'PDF',
            pages: 385,
            image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400&h=500&fit=crop',
            description: 'Essential strategies for building and growing successful businesses in the modern economy.',
        },
        {
            id: 5,
            title: 'Creative Writing Workshop',
            author: 'Emma Wilson',
            category: 'literature',
            price: 2200,
            oldPrice: 4500,
            discount: '-51%',
            rating: 4.4,
            reviews: 78,
            format: 'PDF',
            pages: 298,
            image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=500&fit=crop',
            description: 'Develop your creative writing skills with practical exercises and expert guidance.',
        },
        {
            id: 6,
            title: 'Data Science Fundamentals',
            author: 'Robert Lee',
            category: 'technology',
            price: 4000,
            oldPrice: 8000,
            discount: '-50%',
            rating: 4.9,
            reviews: 203,
            format: 'PDF',
            pages: 512,
            image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=500&fit=crop',
            description: 'Learn data science fundamentals and practical applications for real-world problems.',
        },
        {
            id: 7,
            title: 'Financial Freedom Blueprint',
            author: 'James Anderson',
            category: 'business',
            price: 5000,
            oldPrice: 7500,
            discount: '-49%',
            rating: 4.7,
            reviews: 165,
            format: 'PDF',
            pages: 320,
            image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&h=500&fit=crop',
            description: 'A comprehensive guide to achieving financial independence through smart investing and planning.',
        },
        {
            id: 8,
            title: 'Mindfulness and Meditation',
            author: 'Dr. Lisa Chen',
            category: 'personal-development',
            price: 2400,
            oldPrice: 4800,
            discount: '-50%',
            rating: 4.6,
            reviews: 142,
            format: 'PDF',
            pages: 245,
            image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=500&fit=crop',
            description: 'Discover inner peace and reduce stress through proven mindfulness techniques.',
        },
        {
            id: 9,
            title: 'Web Development Bootcamp',
            author: 'Alex Thompson',
            category: 'technology',
            price: 3500,
            oldPrice: 7000,
            discount: '-50%',
            rating: 4.8,
            reviews: 198,
            format: 'PDF',
            pages: 450,
            image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=500&fit=crop',
            description: 'Complete web development course covering HTML, CSS, JavaScript, and modern frameworks.',
        },
        {
            id: 10,
            title: 'Leadership Excellence',
            author: 'Marcus Williams',
            category: 'business',
            price: 3200,
            oldPrice: 6400,
            discount: '-50%',
            rating: 4.5,
            reviews: 134,
            format: 'PDF',
            pages: 310,
            image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=500&fit=crop',
            description: 'Transform your leadership skills and inspire your team to achieve greatness.',
        },
        {
            id: 11,
            title: 'The Art of Learning',
            author: 'Josh Waitzkin',
            category: 'education',
            price: 2500,
            oldPrice: 5000,
            discount: '-50%',
            rating: 4.5,
            reviews: 124,
            format: 'PDF',
            pages: 256,
            image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=500&fit=crop',
            description: 'A comprehensive guide to mastering the art of learning and skill development.',
        },
        {
            id: 12,
            title: 'Make It Stick: The Science of Successful Learning',
            author: 'Peter C. Brown',
            category: 'education',
            price: 3000,
            oldPrice: 6000,
            discount: '-50%',
            rating: 4.7,
            reviews: 156,
            format: 'PDF',
            pages: 336,
            image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=500&fit=crop',
            description: 'Revolutionary methods for effective learning backed by cognitive science.',
        },
        {
            id: 13,
            title: 'The First 20 Hours: Master Any Skill',
            author: 'Josh Kaufman',
            category: 'education',
            price: 2200,
            oldPrice: 4400,
            discount: '-50%',
            rating: 4.4,
            reviews: 98,
            format: 'PDF',
            pages: 288,
            image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400&h=500&fit=crop',
            description: 'Learn how to rapidly acquire new skills in just 20 hours of practice.',
        },

        // ==================
        // BUSINESS BOOKS
        // ==================
        {
            id: 14,
            title: 'Digital Marketing Mastery',
            author: 'Sarah Johnson',
            category: 'business',
            price: 3200,
            oldPrice: 6500,
            discount: '-51%',
            rating: 4.8,
            reviews: 89,
            format: 'PDF',
            pages: 342,
            image: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&h=500&fit=crop',
            description: 'Master digital marketing strategies and grow your online presence.',
        },
        {
            id: 15,
            title: 'Business Strategy Essentials',
            author: 'David Miller',
            category: 'business',
            price: 3500,
            oldPrice: 7000,
            discount: '-50%',
            rating: 4.6,
            reviews: 92,
            format: 'PDF',
            pages: 385,
            image: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400&h=500&fit=crop',
            description: 'Essential strategies for building and growing successful businesses.',
        },
        {
            id: 16,
            title: 'Financial Freedom Blueprint',
            author: 'James Anderson',
            category: 'business',
            price: 3800,
            oldPrice: 7500,
            discount: '-49%',
            rating: 4.7,
            reviews: 165,
            format: 'PDF',
            pages: 320,
            image: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400&h=500&fit=crop',
            description: 'A comprehensive guide to achieving financial independence.',
        },
        {
            id: 17,
            title: 'Leadership Excellence',
            author: 'Marcus Williams',
            category: 'business',
            price: 3200,
            oldPrice: 6400,
            discount: '-50%',
            rating: 4.5,
            reviews: 134,
            format: 'PDF',
            pages: 310,
            image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=500&fit=crop',
            description: 'Transform your leadership skills and inspire your team.',
        },
        {
            id: 18,
            title: 'The Lean Startup',
            author: 'Eric Ries',
            category: 'business',
            price: 2800,
            oldPrice: 5600,
            discount: '-50%',
            rating: 4.6,
            reviews: 203,
            format: 'PDF',
            pages: 296,
            image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=500&fit=crop',
            description: 'How to use continuous innovation to create radically successful businesses.',
        },

        // ==================
        // TECHNOLOGY BOOKS
        // ==================
        {
            id: 19,
            title: 'Python Programming Guide',
            author: 'Michael Chen',
            category: 'technology',
            price: 2800,
            oldPrice: 5500,
            discount: '-49%',
            rating: 4.7,
            reviews: 156,
            format: 'PDF',
            pages: 428,
            image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=500&fit=crop',
            description: 'Complete Python programming guide from basics to advanced concepts.',
        },
        {
            id: 20,
            title: 'Data Science Fundamentals',
            author: 'Robert Lee',
            category: 'technology',
            price: 4000,
            oldPrice: 8000,
            discount: '-50%',
            rating: 4.9,
            reviews: 203,
            format: 'PDF',
            pages: 512,
            image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=500&fit=crop',
            description: 'Learn data science fundamentals and practical applications.',
        },
        {
            id: 21,
            title: 'Web Development Bootcamp',
            author: 'Alex Thompson',
            category: 'technology',
            price: 3500,
            oldPrice: 7000,
            discount: '-50%',
            rating: 4.8,
            reviews: 198,
            format: 'PDF',
            pages: 450,
            image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=500&fit=crop',
            description: 'Complete web development course covering HTML, CSS, JavaScript.',
        },
        {
            id: 22,
            title: 'Machine Learning A-Z',
            author: 'Dr. Amanda Foster',
            category: 'technology',
            price: 4500,
            oldPrice: 9000,
            discount: '-50%',
            rating: 4.9,
            reviews: 267,
            format: 'PDF',
            pages: 580,
            image: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=500&fit=crop',
            description: 'Comprehensive guide to machine learning algorithms and applications.',
        },
        {
            id: 23,
            title: 'Cloud Computing Essentials',
            author: 'Kevin Martinez',
            category: 'technology',
            price: 3200,
            oldPrice: 6400,
            discount: '-50%',
            rating: 4.6,
            reviews: 145,
            format: 'PDF',
            pages: 392,
            image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=500&fit=crop',
            description: 'Master AWS, Azure, and Google Cloud Platform fundamentals.',
        },

        // ==================
        // PERSONAL DEVELOPMENT BOOKS
        // ==================
        {
            id: 24,
            title: 'Mindfulness and Meditation',
            author: 'Dr. Lisa Chen',
            category: 'personal development',
            price: 2400,
            oldPrice: 4800,
            discount: '-50%',
            rating: 4.6,
            reviews: 142,
            format: 'PDF',
            pages: 245,
            image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=500&fit=crop',
            description: 'Discover inner peace and reduce stress through mindfulness.',
        },
        {
            id: 25,
            title: 'Atomic Habits',
            author: 'James Clear',
            category: 'personal development',
            price: 2700,
            oldPrice: 5400,
            discount: '-50%',
            rating: 4.9,
            reviews: 312,
            format: 'PDF',
            pages: 320,
            image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=500&fit=crop',
            description: 'Tiny changes that lead to remarkable results.',
        },
        {
            id: 26,
            title: 'The Power of Now',
            author: 'Eckhart Tolle',
            category: 'personal development',
            price: 2500,
            oldPrice: 5000,
            discount: '-50%',
            rating: 4.7,
            reviews: 198,
            format: 'PDF',
            pages: 236,
            image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&h=500&fit=crop',
            description: 'A guide to spiritual enlightenment and living in the present.',
        },

        // ==================
        // LITERATURE BOOKS
        // ==================
        {
            id: 27,
            title: 'Creative Writing Workshop',
            author: 'Emma Wilson',
            category: 'literature',
            price: 2200,
            oldPrice: 4500,
            discount: '-51%',
            rating: 4.4,
            reviews: 78,
            format: 'PDF',
            pages: 298,
            image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=500&fit=crop',
            description: 'Develop your creative writing skills with practical exercises.',
        },
        {
            id: 28,
            title: 'The Elements of Style',
            author: 'William Strunk Jr.',
            category: 'literature',
            price: 1800,
            oldPrice: 3600,
            discount: '-50%',
            rating: 4.8,
            reviews: 234,
            format: 'PDF',
            pages: 105,
            image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=500&fit=crop',
            description: 'The classic writing style guide every writer needs.',
        },

        // ==================
        // SCIENCE BOOKS
        // ==================
        {
            id: 29,
            title: 'A Brief History of Time',
            author: 'Stephen Hawking',
            category: 'science',
            price: 3500,
            oldPrice: 7000,
            discount: '-50%',
            rating: 4.8,
            reviews: 456,
            format: 'PDF',
            pages: 256,
            image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=400&h=500&fit=crop',
            description: 'From the Big Bang to black holes, explore the universe.',
        },
        {
            id: 30,
            title: 'The Selfish Gene',
            author: 'Richard Dawkins',
            category: 'science',
            price: 3200,
            oldPrice: 6400,
            discount: '-50%',
            rating: 4.7,
            reviews: 289,
            format: 'PDF',
            pages: 384,
            image: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=400&h=500&fit=crop',
            description: 'Revolutionary perspective on evolution and natural selection.',
        },

        // ==================
        // HEALTH & WELLNESS BOOKS
        // ==================
        {
            id: 31,
            title: 'The Body Keeps the Score',
            author: 'Bessel van der Kolk',
            category: 'health wellness',
            price: 3300,
            oldPrice: 6600,
            discount: '-50%',
            rating: 4.8,
            reviews: 412,
            format: 'PDF',
            pages: 464,
            image: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400&h=500&fit=crop',
            description: 'Brain, mind, and body in the healing of trauma.',
        },
        {
            id: 32,
            title: 'How Not to Die',
            author: 'Dr. Michael Greger',
            category: 'health wellness',
            price: 3000,
            oldPrice: 6000,
            discount: '-50%',
            rating: 4.6,
            reviews: 298,
            format: 'PDF',
            pages: 576,
            image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400&h=500&fit=crop',
            description: 'Discover foods scientifically proven to prevent and reverse disease.',
        },

        // ==================
        // HISTORY BOOKS
        // ==================
        {
            id: 33,
            title: 'Sapiens: A Brief History of Humankind',
            author: 'Yuval Noah Harari',
            category: 'history',
            price: 3500,
            oldPrice: 7000,
            discount: '-50%',
            rating: 4.9,
            reviews: 567,
            format: 'PDF',
            pages: 512,
            image: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=400&h=500&fit=crop',
            description: 'The story of how humans conquered the world.',
        },
        {
            id: 34,
            title: 'The History of Ancient Rome',
            author: 'Garrett G. Fagan',
            category: 'history',
            price: 2800,
            oldPrice: 5600,
            discount: '-50%',
            rating: 4.5,
            reviews: 187,
            format: 'PDF',
            pages: 368,
            image: 'https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=400&h=500&fit=crop',
            description: 'Comprehensive history of the Roman Empire.',
        },

        // ==================
        // ARTS & CULTURE BOOKS
        // ==================
        {
            id: 35,
            title: 'The Story of Art',
            author: 'E.H. Gombrich',
            category: 'arts culture',
            price: 4000,
            oldPrice: 8000,
            discount: '-50%',
            rating: 4.8,
            reviews: 234,
            format: 'PDF',
            pages: 688,
            image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=500&fit=crop',
            description: 'One of the most famous and popular books on art ever written.',
        },
        {
            id: 36,
            title: 'Music Theory for Beginners',
            author: 'Nicolas Carter',
            category: 'arts culture',
            price: 2400,
            oldPrice: 4800,
            format: 'PDF',
            pages: 224,
            image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=500&fit=crop',
            description: 'Learn to read music and understand musical concepts.',
        },
       {
            id: 37,
            title: "The Teen Survival Guide to Dating & Relating",
            author: "Annie Fox",
            category: 'Relationships && Marriage',
            price: 3700,
            oldPrice: 5000,
            format: 'PDF',
            pages: 258,
            image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=500&fit=crop',
            pdfUrl: "https://drive.google.com/file/d/1ZKDThOuV9yTshjNzRXVjzfc5qSNjn4xo/view", // <-- changed
            previewUrl: "https://drive.google.com/file/d/your-preview-id/view",
            description: 'Real-World Advice on Guys, Girls, Growing Up, and Getting Along.',
            message: 'Being a teen is sometimes tough—no doubt about that. And relationship issues are part of the challenge. But these issues can be worked out. I believe that having'
        }

    ];

    export const getBooksByCategory = (categorySlug) => {
        return booksData.filter(book => {
            const bookCategory = book.category?.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-');
            return bookCategory === categorySlug;
        });
    };

    // Helper function to get all categories
    export const getAllCategories = () => {
        return [
            'Education',
            'Personal Development',
            'Business',
            'Technology',
            'Science',
            'Literature',
            'Health & Wellness',
            'History',
            'Arts & Culture'
        ];
    };