// lib/booksData.js

// Platform Owner Details
export const PLATFORM_OWNER = {
    sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
    sellerName: 'LAN Library',
    sellerEmail: 'lanlibrarydocs@gmail.com',
    sellerPhone: '07013725529',
    accountType: 'platform_owner'
};

export const booksData = [
    {
        id: 38,
        title: "Sexuality is Invented",
        author: "Brown Oziomachi",
        category: 'Sex Education',
        price: 3500,
        oldPrice: 5000,
        discount: '-30%',
        rating: 4.5,
        reviews: 45,
        format: 'PDF',
        pages: 7,
        pdfUrl: "https://drive.google.com/file/d/1itrjVIaT--5P1ucZL_lBE1nJFErLx-pC/view",
        driveFileId: "1itrjVIaT--5P1ucZL_lBE1nJFErLx-pC",
        embedUrl: "https://drive.google.com/file/d/1itrjVIaT--5P1ucZL_lBE1nJFErLx-pC/preview",
        description: 'When you were a child, what reproductive organ someone had did not matter to you but the moment hormones started playing within you, you cannot think of the outside world. There is nothing strange about it, it is just that your hormones have hijacked your intelligence. Your whole intelligence has been completely hijacked by your hormones. You must understand that Sex is a change that happens with adolescence, and is a simple drive within us. Hormones are the drivers of human reproduction, responsible for sexual development and controlling of menstrual cycle.',
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 39,
        title: "On Generation and Corruption",
        author: "Aristotle",
        category: 'Philosophy',
        price: 4500,
        oldPrice: 6500,
        discount: '-31%',
        rating: 4.8,
        reviews: 156,
        format: 'PDF',
        pages: 55,
        pdfUrl: "https://drive.google.com/file/d/1oY66eDT_drRDCnCYjzm8V6DCWrG2duwg/view",
        driveFileId: "1oY66eDT_drRDCnCYjzm8V6DCWrG2duwg",
        embedUrl: "https://drive.google.com/file/d/1oY66eDT_drRDCnCYjzm8V6DCWrG2duwg/preview",
        description: 'Now that we have established the preceding distinctions, we must first consider whether there is anything which comes-to-be and passes-away in the unqualified sense: or whether nothing comes-to-be in this strict sense, but everything always comes-to-be something and out of something- I mean, e.g. comes-to-be-healthy out of being-ill and ill out of being-healthy, comes-to-be-small out of being-big and big out of being-small, and so on in every other instance.',
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 40,
        title: "The Social Contract or Principles of Political Right",
        author: "Jean Jacques Rousseau",
        category: 'Philosophy',
        price: 5000,
        oldPrice: 7000,
        discount: '-29%',
        rating: 4.9,
        reviews: 234,
        format: 'PDF',
        pages: 66,
        pdfUrl: "https://drive.google.com/file/d/1KrvCyjf7wssPZ-tr5JX-UZBxnH7GaG36/view",
        driveFileId: "1KrvCyjf7wssPZ-tr5JX-UZBxnH7GaG36",
        embedUrl: "https://drive.google.com/file/d/1KrvCyjf7wssPZ-tr5JX-UZBxnH7GaG36/preview",
        description: 'MAN is born free; and everywhere he is in chains. One thinks himself the master of others, and still remains a greater slave than they. How did this change come about? I do not know. What can make it legitimate? That question I think I can answer. If I took into account only force, and the effects derived from it, I should say: "As long as a people is compelled to obey, and obeys, it does well; as soon as it can shake off the yoke, and shakes it off, it does still better; for, regaining its liberty by the same right as took it away, either it is justified in resuming it, or there was no justification for those who took it away." But the social order is a sacred right which is the basis of all other rights.',
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 41,
        title: "Facilitating Effective Teaching through Learning Styles and Thinking",
        author: "Siti Aisyah Ginting",
        category: 'Education',
        price: 3000,
        oldPrice: 4500,
        discount: '-33%',
        rating: 4.6,
        reviews: 78,
        format: 'PDF',
        pages: 9,
        pdfUrl: "https://drive.google.com/file/d/1Q_ZPJPy0uSdeYTiTmjcPmzF7Yk7bskki/view",
        driveFileId: "1Q_ZPJPy0uSdeYTiTmjcPmzF7Yk7bskki",
        embedUrl: "https://drive.google.com/file/d/1Q_ZPJPy0uSdeYTiTmjcPmzF7Yk7bskki/preview",
        description: 'The study deals with learning styles and ways of thinking in facilitating effective teaching. The objective of this study was to investigate the relationship between students\' learning style and ways of thinking toward effective teaching. This study was conducted by using correlational design. The population of the study were 360 university students of English education academic year 2015/2016 in State University of Medan. The samples were 82 university students selected by using random sampling. The data were collected by using questionnaires and tests.',
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 42,
        title: "Classical Political Philosophy and Modern Democracy",
        author: "Rebekkah Brainerd",
        category: 'Philosophy',
        price: 3500,
        oldPrice: 5000,
        discount: '-30%',
        rating: 4.7,
        reviews: 92,
        format: 'PDF',
        pages: 9,
        pdfUrl: "https://drive.google.com/file/d/17NwvgJbBK4g_bhD8IRz8tweT-i28bR8k/view",
        driveFileId: "17NwvgJbBK4g_bhD8IRz8tweT-i28bR8k",
        embedUrl: "https://drive.google.com/file/d/17NwvgJbBK4g_bhD8IRz8tweT-i28bR8k/preview",
        description: 'This paper will be looking at the classical political theories of Plato, Aristotle and Thucydides on democracy to prove they are still relevant and applicable, as well as looking into the problem of democratic corruption.',
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 43,
        title: "What is Collaborative Learning",
        author: "Barbara Leigh Smith, Jean T MacGregor",
        category: 'Education',
        price: 5500,
        oldPrice: 7500,
        discount: '-27%',
        rating: 4.8,
        reviews: 167,
        format: 'PDF',
        pages: 97,
        pdfUrl: "https://drive.google.com/file/d/1dPnqYn_B3RRhnZSwWmQwPim4XAAo_jVl/view",
        driveFileId: "1dPnqYn_B3RRhnZSwWmQwPim4XAAo_jVl",
        embedUrl: "https://drive.google.com/file/d/1dPnqYn_B3RRhnZSwWmQwPim4XAAo_jVl/preview",
        description: 'Collaborative learning is particularly timely now. In the 1980\'s an avalanche of reports underscored the problems of undergraduate education: the distance between faculty and students, the fragmentation of the curriculum, a prevailing pedagogy of lecture and routinized tests, an educational culture that reinforces student passivity, high rates of student attrition, and a reward system that gives low priority to teaching. Collaborative learning, with its emphasis on social and intellectual engagement and mutual responsibility, aims to counteract many of these educational and societal trends.',
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 44,
        title: "Associative Learning and Behaviour: An Algebraic Approach to Symmetries",
        author: "Eduardo Alonso, Esther Mondragon",
        category: 'Psychology',
        price: 4000,
        oldPrice: 6000,
        discount: '-33%',
        rating: 4.7,
        reviews: 103,
        format: 'PDF',
        pages: 27,
        pdfUrl: "https://drive.google.com/file/d/1ndTMkrcfHeoqkZVfzpQz2-WheDg89fkI/view",
        driveFileId: "1ndTMkrcfHeoqkZVfzpQz2-WheDg89fkI",
        embedUrl: "https://drive.google.com/file/d/1ndTMkrcfHeoqkZVfzpQz2-WheDg89fkI/preview",
        description: 'The ability of animals to recognise and adapt to patterns of stimuli and to form causal links in dynamic environments is essential for their survival. Associative learning studies how animals learn (that is, how they acquire information) and behave (that is, how what has been learned is expressed in their behaviour) and is, therefore, of paramount importance in Psychology. Models of associative learning have proved to be relevant to human learning both theoretically and in practice in such diverse areas as behavioural therapy, drug addiction rehabilitation, or anticipatory nausea in cancer treatment.',
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 45,
        title: "Types of Learning",
        author: "Maike Looß",
        category: 'Education',
        price: 4500,
        oldPrice: 6500,
        discount: '-31%',
        rating: 4.6,
        reviews: 124,
        format: 'PDF',
        pages: 40,
        pdfUrl: "https://drive.google.com/file/d/1Xytbaw6wmWRirlDn1de1pNfVP2c4wI2U/view",
        driveFileId: "1Xytbaw6wmWRirlDn1de1pNfVP2c4wI2U",
        embedUrl: "https://drive.google.com/file/d/1Xytbaw6wmWRirlDn1de1pNfVP2c4wI2U/preview",
        description: 'Learning type 1: auditive learning (by listening and speaking), Learning type 2: visual learning (through the eyes, by watching), Learning type 3: haptic learning (by touching and feeling), Learning type 4: learning through the intellect. This kind of classification calls for a critical analysis. Learning type 1 to 3 differ in the kind of receptive channel (sensory mode) for an information. Logically the fourth type of learning does not fit into this category.',
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 46,
        title: "Learners and the Learning Process",
        author: "Ismail Thamarasseri",
        category: 'Education',
        price: 3000,
        oldPrice: 4500,
        discount: '-33%',
        rating: 4.5,
        reviews: 87,
        format: 'PDF',
        pages: 9,
        pdfUrl: "https://drive.google.com/file/d/1lqf68yJc1yb7BB_XheIK65T-yUc0y3jS/view",
        driveFileId: "1lqf68yJc1yb7BB_XheIK65T-yUc0y3jS",
        embedUrl: "https://drive.google.com/file/d/1lqf68yJc1yb7BB_XheIK65T-yUc0y3jS/preview",
        description: 'For a long period our system of education especially school education centred on teacher. Now there is change. The Learner came to limelight. The learner plays a pivotal role in the education process. There are five dispositions that the learner should have to help them become active and autonomous learners: be inquisitive, take initiative, be confident, be inventive, and be reflective. First, the learner should be inquisitive. An inquisitive learner is one that asks many questions and wants to find out new information and will investigate.',
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 47,
        title: "The Effect of Discovery Learning Method Application",
        author: "Education Resources Information Center",
        category: 'Education',
        price: 3500,
        oldPrice: 5000,
        discount: '-30%',
        rating: 4.6,
        reviews: 95,
        format: 'PDF',
        pages: 16,
        pdfUrl: "https://drive.google.com/file/d/1UPXcNHvhrjv4Zac_Acg-fvk5UZnFYIHH/view",
        driveFileId: "1UPXcNHvhrjv4Zac_Acg-fvk5UZnFYIHH",
        embedUrl: "https://drive.google.com/file/d/1UPXcNHvhrjv4Zac_Acg-fvk5UZnFYIHH/preview",
        description: 'Discovery Learning is a learning method that encourages students to ask questions and formulate their own tentative answers, and to deduce general principles from practical examples or experiences. Other definition states that Discovery Learning is a learning situation in which the principal content of what is to be learned is not given but must be independently discovered by the student.',
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 1,
        title: "The Ultimate Guide to Growing YouTube Subscribers",
        author: "Erica Lam",
        category: 'Social Media',
        price: 2800,
        oldPrice: 4000,
        discount: '-30%',
        rating: 4.7,
        reviews: 142,
        format: 'PDF',
        pages: 30,
        pdfUrl: "https://drive.google.com/file/d/1gZz53JTr_NERzqb16crEMi31wt4qhwTp/view?usp=sharing",
        driveFileId: "1gZz53JTr_NERzqb16crEMi31wt4qhwTp",
        embedUrl: "https://drive.google.com/file/d/1gZz53JTr_NERzqb16crEMi31wt4qhwTp/preview",
        description: "Growing a YouTube channel is no walk in the park! Figuring out your niche, perfecting your content, and figuring out how to get views and subscribers – it's hard work! But it's worth it because you LOVE creating and building your community. This eBook features collaboration with 14 YouTube creators who have built communities ranging from 10,000 subscribers to half a million! Learn their secrets and the steps they took to get where they are today.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 2,
        title: "Jim Stoppani's 12-Week Shortcut to Size",
        author: "Bodybuilding.com",
        category: 'Health & Fitness',
        price: 2500,
        oldPrice: 3500,
        discount: '-29%',
        rating: 4.8,
        reviews: 218,
        format: 'PDF',
        pages: 14,
        pdfUrl: "https://drive.google.com/file/d/19JrxamaIxsBcYZK80k8u7SJQuhAsstas/view?usp=sharing",
        driveFileId: "19JrxamaIxsBcYZK80k8u7SJQuhAsstas",
        embedUrl: "https://drive.google.com/file/d/19JrxamaIxsBcYZK80k8u7SJQuhAsstas/preview",
        description: "The 12-week program based on one of the oldest, tried and true methods for gaining strength and muscle. This type of training has successfully prepared almost every type of athlete imaginable, from Olympic weightlifters to soccer players. This basic, but very effective program has been tweaked to perfect its effectiveness and to maximize results including greater strength, bigger muscles, and less body fat.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 3,
        title: "Acres of Diamonds",
        author: "Russell H. Conwell",
        category: 'Personal Development',
        price: 3200,
        oldPrice: 4500,
        discount: '-29%',
        rating: 4.5,
        reviews: 167,
        format: 'PDF',
        pages: 51,
        pdfUrl: "https://drive.google.com/file/d/1NEgt1KpRw3CC28_xVP2D_PenVsLnYpbq/view?usp=sharing",
        driveFileId: "1NEgt1KpRw3CC28_xVP2D_PenVsLnYpbq",
        embedUrl: "https://drive.google.com/file/d/1NEgt1KpRw3CC28_xVP2D_PenVsLnYpbq/preview",
        description: "A timeless collection of stories curious and weird, ancient and modern, strange and familiar. Travel down the Tigris and Euphrates rivers with an old Arab guide who shares profound wisdom through captivating tales. This classic work reveals the diamonds of opportunity that lie right in your own backyard, teaching valuable lessons about recognizing and seizing the potential that surrounds you.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 4,
        title: "Trainer Tips: Hypertrophy",
        author: "National Strength and Conditioning Association",
        category: 'Health & Fitness',
        price: 1500,
        oldPrice: 2000,
        discount: '-25%',
        rating: 4.6,
        reviews: 89,
        format: 'PDF',
        pages: 2,
        pdfUrl: "https://drive.google.com/file/d/1GteaLNuO347R4lDNHd3IemFEjXmiYJ7B/view?usp=sharing",
        driveFileId: "1GteaLNuO347R4lDNHd3IemFEjXmiYJ7B",
        embedUrl: "https://drive.google.com/file/d/1GteaLNuO347R4lDNHd3IemFEjXmiYJ7B/preview",
        description: "Muscle hypertrophy is an increase in the size of a muscle, or its cross-sectional area attributed to an increase in the size and/or number of myofibrils (actin and myosin) within a given muscle fiber. Learn how hypertrophy occurs in both type I and type II muscle fibers but to a greater extent in type II muscle fibers. Essential guide from fitness professionals.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 5,
        title: "The Science of Interpersonal Trust",
        author: "Dr. Randy Borum",
        category: 'Science',
        price: 4500,
        oldPrice: 6500,
        discount: '-31%',
        rating: 4.7,
        reviews: 134,
        format: 'PDF',
        pages: 88,
        pdfUrl: "https://drive.google.com/file/d/17Z6dGd_LV-PSIMqz5v1MFSt_64a1jvN9/view?usp=sharing",
        driveFileId: "17Z6dGd_LV-PSIMqz5v1MFSt_64a1jvN9",
        embedUrl: "https://drive.google.com/file/d/17Z6dGd_LV-PSIMqz5v1MFSt_64a1jvN9/preview",
        description: "This document summarizes the state of the art in interpersonal trust research, describing how researchers define trust and its components, exploring theories about how people decide whether to trust, and describing how trust may work differently for some people than for others. Understanding trust is essential for improving performance of individuals and their organizations, as well as honing their competitive advantage.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 6,
        title: "Physical Education, Physical Activity and Sport for Young People",
        author: "Department of Education and Skills",
        category: 'Education',
        price: 4200,
        oldPrice: 6000,
        discount: '-30%',
        rating: 4.4,
        reviews: 76,
        format: 'PDF',
        pages: 84,
        pdfUrl: "https://drive.google.com/file/d/1TJFQgeCsL-sXd8rzxmKODT0dcgRR4vL9/view?usp=sharing",
        driveFileId: "1TJFQgeCsL-sXd8rzxmKODT0dcgRR4vL9",
        embedUrl: "https://drive.google.com/file/d/1TJFQgeCsL-sXd8rzxmKODT0dcgRR4vL9/preview",
        description: "This government document promotes physical education, physical activity and sport in recognition of the educational, social, health and cultural benefits that can be gained through participation. A series of measures has been adopted to promote awareness and action related to the cultivation of a more active, physically educated and healthier society, including the development of a national physical activity plan and the establishment of the Active School Flag.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 7,
        title: "Associative Learning and Behaviour: An Algebraic Symmetries",
        author: "Eduardo Alonso & Esther Mondragon",
        category: 'Psychology',
        price: 3800,
        oldPrice: 5500,
        discount: '-31%',
        rating: 4.3,
        reviews: 52,
        format: 'PDF',
        pages: 40,
        pdfUrl: "https://drive.google.com/file/d/1ndTMkrcfHeoqkZVfzpQz2-WheDg89fkI/view?usp=sharing",
        driveFileId: "1ndTMkrcfHeoqkZVfzpQz2-WheDg89fkI",
        embedUrl: "https://drive.google.com/file/d/1ndTMkrcfHeoqkZVfzpQz2-WheDg89fkI/preview",
        description: "The ability of animals to recognise and adapt to patterns of stimuli and to form causal links in dynamic environments is essential for their survival. Associative learning studies how animals learn and behave and is of paramount importance in Psychology. Models of associative learning have proved to be relevant to human learning both theoretically and in practice in diverse areas as behavioural therapy, drug addiction rehabilitation, and anticipatory nausea in cancer treatment.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 8,
        title: "The Law of Success",
        author: "Napoleon Hill",
        category: 'Personal Development',
        price: 8500,
        oldPrice: 12000,
        discount: '-29%',
        rating: 4.9,
        reviews: 542,
        format: 'PDF',
        pages: 1170,
        pdfUrl: "https://drive.google.com/file/d/1gRVO0wTD4fXf-8v2-6rTYVxVxKp6kPeL/view?usp=sharing",
        driveFileId: "1gRVO0wTD4fXf-8v2-6rTYVxVxKp6kPeL",
        embedUrl: "https://drive.google.com/file/d/1gRVO0wTD4fXf-8v2-6rTYVxVxKp6kPeL/preview",
        description: "This course is the result of careful analysis of the life-work of over one hundred men and women who have achieved unusual success in their respective callings. The author has spent more than twenty years in gathering, classifying, testing and organizing the Fifteen Laws upon which the course is based. A comprehensive masterpiece on achieving success through proven principles and strategies.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 9,
        title: "The Imitation of Christ",
        author: "Thomas à Kempis",
        category: 'Religion & Spirituality',
        price: 5500,
        oldPrice: 8000,
        discount: '-31%',
        rating: 4.8,
        reviews: 387,
        format: 'PDF',
        pages: 223,
        pdfUrl: "https://drive.google.com/file/d/1awmQopYFJmE2gTWMq_3WvuHcIfduv0jG/view?usp=sharing",
        driveFileId: "1awmQopYFJmE2gTWMq_3WvuHcIfduv0jG",
        embedUrl: "https://drive.google.com/file/d/1awmQopYFJmE2gTWMq_3WvuHcIfduv0jG/preview",
        description: "With the exception of the Bible, no Christian writing has had so wide a vogue or so sustained a popularity as this. Its structure owes largely to the writings of the medieval mystics, and its ideas and phrases are a mosaic from the Bible and the Fathers of the early Church. These elements are interwoven with such delicate skill and a religious feeling at once so ardent and so sound, that it promises to remain the supreme call and guide to spiritual aspiration.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 10,
        title: "Self-Help",
        author: "Samuel Smiles",
        category: 'Self-Help',
        price: 6200,
        oldPrice: 9000,
        discount: '-31%',
        rating: 4.6,
        reviews: 294,
        format: 'PDF',
        pages: 344,
        pdfUrl: "https://drive.google.com/file/d/15UcBeXm-D1NwLDr3bQHfpNGHvfW2Yjjh/view?usp=sharing",
        driveFileId: "15UcBeXm-D1NwLDr3bQHfpNGHvfW2Yjjh",
        embedUrl: "https://drive.google.com/file/d/15UcBeXm-D1NwLDr3bQHfpNGHvfW2Yjjh/preview",
        description: "The object of this book is to re-inculcate old-fashioned but wholesome lessons—that youth must work in order to enjoy, that nothing creditable can be accomplished without application and diligence, that the student must not be daunted by difficulties but conquer them by patience and perseverance, and that above all, one must seek elevation of character. A timeless classic on personal development and success.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2 ',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 11,
        title: "The Life Triumphant",
        author: "James Allen",
        category: 'Self-Help',
        price: 3000,
        oldPrice: 4200,
        discount: '-29%',
        rating: 4.7,
        reviews: 156,
        format: 'PDF',
        pages: 37,
        pdfUrl: "https://drive.google.com/file/d/1JVKEfvUjtr_HEU6ofeFuyHG6VlzX45mn/view?usp=sharing",
        driveFileId: "1JVKEfvUjtr_HEU6ofeFuyHG6VlzX45mn",
        embedUrl: "https://drive.google.com/file/d/1JVKEfvUjtr_HEU6ofeFuyHG6VlzX45mn/preview",
        description: "For those who will fight bravely and not yield, there is triumphant victory over all the dark things of life. To stand face to face with truth; to arrive, after innumerable wanderings and pains, at wisdom and bliss; not to be finally defeated and cast out, but ultimately to triumph over every inward foe—such is man's divine destiny, such his glorious goal. This book shows the elements in character and conduct which go to build up the life of calm strength and superlative victory.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 12,
        title: "As a Man Thinketh",
        author: "James Allen",
        category: 'Self-Help',
        price: 2200,
        oldPrice: 3000,
        discount: '-27%',
        rating: 4.8,
        reviews: 421,
        format: 'PDF',
        pages: 17,
        pdfUrl: "https://drive.google.com/file/d/1D76wIcK2rx-QBrnpGLk7njNZXiBaDdxl/view?usp=sharing",
        driveFileId: "1D76wIcK2rx-QBrnpGLk7njNZXiBaDdxl",
        embedUrl: "https://drive.google.com/file/d/1D76wIcK2rx-QBrnpGLk7njNZXiBaDdxl/preview",
        description: "The aphorism, 'As a man thinketh in his heart so is he,' not only embraces the whole of a man's being, but is so comprehensive as to reach out to every condition and circumstance of his life. A man is literally what he thinks, his character being the complete sum of all his thoughts. As the plant springs from the seed, so every act of a man springs from the hidden seeds of thought. A transformative classic on the power of thought.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 13,
        title: "Building Confidence Workbook",
        author: "Deloitte",
        category: 'Self-Help',
        price: 2400,
        oldPrice: 3500,
        discount: '-31%',
        rating: 4.5,
        reviews: 128,
        format: 'PDF',
        pages: 14,
        pdfUrl: "https://drive.google.com/file/d/1v5slycc0nFXW3A4vL7jnrqyu8c9adqOW/view?usp=sharing",
        driveFileId: "1v5slycc0nFXW3A4vL7jnrqyu8c9adqOW",
        embedUrl: "https://drive.google.com/file/d/1v5slycc0nFXW3A4vL7jnrqyu8c9adqOW/preview",
        description: "When talking to yourself, your internal voice and the language you use may be more negative than positive. The way you talk to yourself can impact your confidence and the way you feel about yourself. This workbook provides practical ways to improve the way you talk to yourself, build on your confidence and practice self-compassion with actionable exercises and techniques.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 14,
        title: "Supplement Guide: Reducing Supplement Risk",
        author: "U.S. Anti-Doping Agency (USADA)",
        category: 'Health & Fitness',
        price: 2800,
        oldPrice: 4000,
        discount: '-30%',
        rating: 4.4,
        reviews: 87,
        format: 'PDF',
        pages: 21,
        pdfUrl: "https://drive.google.com/file/d/1eTor-IexxR3zlJ-Ka9hdtRy1r2D-zFAZ/view?usp=sharing",
        driveFileId: "1eTor-IexxR3zlJ-Ka9hdtRy1r2D-zFAZ",
        embedUrl: "https://drive.google.com/file/d/1eTor-IexxR3zlJ-Ka9hdtRy1r2D-zFAZ/preview",
        description: "Many athletes believe they need dietary supplements to perform at their best, but people regularly overestimate the benefits and safety. Many use dietary supplements without understanding the supplement industry. Dietary supplements are regulated in a post-market manner, meaning the FDA does not evaluate the contents or effects of supplements before they are sold. Learn how to reduce supplement risk and make informed decisions about supplementation.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 15,
        title: "The Power of Concentration",
        author: "William Walker Atkinson",
        category: 'Self-Help',
        price: 4000,
        oldPrice: 5500,
        discount: '-27%',
        rating: 4.6,
        reviews: 203,
        format: 'PDF',
        pages: 76,
        pdfUrl: "https://drive.google.com/file/d/1k96pYjEwLkrEQ8wGbAS7ysUnH4j5iMSR/view?usp=sharing",
        driveFileId: "1k96pYjEwLkrEQ8wGbAS7ysUnH4j5iMSR",
        embedUrl: "https://drive.google.com/file/d/1k96pYjEwLkrEQ8wGbAS7ysUnH4j5iMSR/preview",
        description: "We all know that in order to accomplish a certain thing we must concentrate. It is of the utmost value to learn how to concentrate. To make a success of anything you must be able to concentrate your entire thought upon the idea you are working out. It seems a peculiar fact that it is easier to concentrate on something that is not good for us, than on something that is beneficial. Learn how to master the art of concentration for success.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 16,
        title: "A Confidence and Self-Esteem Self-Help Workbook",
        author: "Cardiff and Vale University Health Board",
        category: 'Self-Help',
        price: 3500,
        oldPrice: 5000,
        discount: '-30%',
        rating: 4.7,
        reviews: 165,
        format: 'PDF',
        pages: 44,
        pdfUrl: "https://drive.google.com/file/d/1MSWp7jh7RFYFIa9oGYMA5OgPQRXTTGKK/view?usp=sharing",
        driveFileId: "1MSWp7jh7RFYFIa9oGYMA5OgPQRXTTGKK",
        embedUrl: "https://drive.google.com/file/d/1MSWp7jh7RFYFIa9oGYMA5OgPQRXTTGKK/preview",
        description: "Everybody at some point has moments of doubt about their own abilities, appearance, skills or the type of person they are. If you often feel unhappy with yourself or your achievements, or that you are not good enough, this may mean that you are experiencing lower levels of confidence and self-esteem. This comprehensive workbook will benefit you with practical exercises and guidance.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 17,
        title: "Six Ways to Rebuild Trust After a Betrayal",
        author: "Barbara J. Peters",
        category: 'Relationship',
        price: 2000,
        oldPrice: 2800,
        discount: '-29%',
        rating: 4.5,
        reviews: 112,
        format: 'PDF',
        pages: 12,
        pdfUrl: "https://drive.google.com/file/d/1vvgiJX0_DmUPN5ZmM7FY9PDDqUPvP9Kq/view?usp=sharing",
        driveFileId: "1vvgiJX0_DmUPN5ZmM7FY9PDDqUPvP9Kq",
        embedUrl: "https://drive.google.com/file/d/1vvgiJX0_DmUPN5ZmM7FY9PDDqUPvP9Kq/preview",
        description: "Trust is an essential component of a strong relationship. Without trust, chances of survival for the long haul are limited, if not nonexistent. Once trust is broken, it's hard to rebuild. Some people claim that they are not able to trust ever again, and some want the chance to rebuild trust. This eBook is for those who want the chance to rebuild trust with six proven methods.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 18,
        title: "Rules for Bodybuilding and Fitness",
        author: "IFBB (International Federation of BodyBuilding)",
        category: 'Health & Fitness',
        price: 3500,
        oldPrice: 5000,
        discount: '-30%',
        rating: 4.6,
        reviews: 176,
        format: 'PDF',
        pages: 42,
        pdfUrl: "https://drive.google.com/file/d/1gyyJjZC1Y-tmhoChYsAnDdXMaI8_Rwkz/view?usp=sharing",
        driveFileId: "1gyyJjZC1Y-tmhoChYsAnDdXMaI8_Rwkz",
        embedUrl: "https://drive.google.com/file/d/1gyyJjZC1Y-tmhoChYsAnDdXMaI8_Rwkz/preview",
        description: "Official rules and guidelines for bodybuilding and fitness competitions from the International Federation of BodyBuilding. This comprehensive guide covers competition standards, weight classifications, judging criteria, and procedures. Essential reading for any competitor who does not make weight will be given a maximum of thirty minutes to do so. Learn all the official rules and regulations.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 19,
        title: "The Science of Getting Rich",
        author: "Wallace D. Wattles",
        category: 'Finance',
        price: 4200,
        oldPrice: 6000,
        discount: '-30%',
        rating: 4.8,
        reviews: 367,
        format: 'PDF',
        pages: 74,
        pdfUrl: "https://drive.google.com/file/d/1iTyel8n1WIlkAZg5lzsx-WYP_D2ttihw/view?usp=sharing",
        driveFileId: "1iTyel8n1WIlkAZg5lzsx-WYP_D2ttihw",
        embedUrl: "https://drive.google.com/file/d/1iTyel8n1WIlkAZg5lzsx-WYP_D2ttihw/preview",
        description: "This book is pragmatical, not philosophical; a practical manual, not a treatise upon theories. It is intended for the men and women whose most pressing need is for money; who wish to get rich first, and philosophize afterward. It is for those who want results and who are willing to take the conclusions of science as a basis for action, without going into all the processes by which those conclusions were reached.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 20,
        title: "A Simple Guide to Boosting Your Confidence: 20 Easy Tips to Increase Self-Esteem",
        author: "Matt Landry",
        category: 'Self-Help',
        price: 2200,
        oldPrice: 3000,
        discount: '-27%',
        rating: 4.6,
        reviews: 143,
        format: 'PDF',
        pages: 16,
        pdfUrl: "https://drive.google.com/file/d/1tMWOhK_tqgvwzMEuVu-opzVMgCkOLqUF/view?usp=sharing",
        driveFileId: "1tMWOhK_tqgvwzMEuVu-opzVMgCkOLqUF",
        embedUrl: "https://drive.google.com/file/d/1tMWOhK_tqgvwzMEuVu-opzVMgCkOLqUF/preview",
        description: "Of the many things that help us thrive or simply survive in our everyday lives, confidence ranks as among one of the greatest. Confidence in many ways helps determine your career, finances, relationships, and effect you have upon raising a family. It's an important vehicle to happiness, well-being, and a positive mental state. It also has a direct effect on the people around you, both positively (higher confidence) and negatively (lower confidence). Learn 20 practical tips to boost your confidence today.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
     {
        id: 21,
        title: "Bodybuilding Nutrition",
        author: "Skip La Cour",
        category: 'Health & Fitness',
        price: 8500,
        oldPrice: 11000,
        discount: '-23%',
        rating: 4.6,
        reviews: 87,
        format: 'PDF',
        pages: 104,
        pdfUrl: "https://drive.google.com/file/d/1rPWz-yxIQMMlq4aGTF_UomKg9Nz68Yy8/view?usp=sharing",
        driveFileId: "1rPWz-yxIQMMlq4aGTF_UomKg9Nz68Yy8",
        embedUrl: "https://drive.google.com/file/d/1rPWz-yxIQMMlq4aGTF_UomKg9Nz68Yy8/preview",
        description: "Especially true when it comes to nutrition. After answering literally thousands of questions from bodybuilders for more than a decade through seminars, appearances, letters, phone consultations, and contact through the Internet, the same questions were asked and the same challenges were encountered over and over again. It didn't matter what level of experience, number of accomplishments, individual circumstances, or what part of the world a bodybuilder lived, when it comes to nutrition, patterns of thinking and the obstacles faced were basically the same.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
         sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 22,
        title: "Man's Search For Meaning",
        author: "Viktor Frankl",
        category: 'Self-help',
        price: 14500,
        oldPrice: 19000,
        discount: '-24%',
        rating: 4.9,
        reviews: 342,
        format: 'PDF',
        pages: 187,
        pdfUrl: "https://drive.google.com/file/d/1-rGu4eI27QFP65OcYL6jp2Vb7PpbLReH/view?usp=sharing",
        driveFileId: "1-rGu4eI27QFP65OcYL6jp2Vb7PpbLReH",
        embedUrl: "https://drive.google.com/file/d/1-rGu4eI27QFP65OcYL6jp2Vb7PpbLReH/preview",
        description: "Life is meaningful under all circumstances, even the most painful ones, and discovering that meaning gives humans the strength to endure suffering. Viktor Frankl argues that while we cannot always control what happens to us, we can always choose our attitude and response to it. This freedom of choice becomes the foundation of inner strength, dignity, and survival. Man's Search for Meaning is widely regarded as one of the most influential works on psychology, resilience, and the human spirit. Blending personal experiences from Nazi concentration camps with profound psychological insight, the book introduces logotherapy—the idea that the primary drive of human beings is the search for meaning.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 23,
        title: "Guide to Inclusive Physical Education and Sports Activities",
        author: "Special Olympics New Jersey",
        category: 'Sports & Education',
        price: 14000,
        oldPrice: 18500,
        discount: '-24%',
        rating: 4.7,
        reviews: 64,
        format: 'PDF',
        pages: 184,
        pdfUrl: "https://drive.google.com/file/d/1hetLS4f6-0CSKH9PBGXCY8FFlZgwZSCT/view?usp=sharing",
        driveFileId: "1hetLS4f6-0CSKH9PBGXCY8FFlZgwZSCT",
        embedUrl: "https://drive.google.com/file/d/1hetLS4f6-0CSKH9PBGXCY8FFlZgwZSCT/preview",
        description: "The transformative power of sports to change lives is at the core of the Special Olympics Movement. Through the power and joy of sports, environments of acceptance, respect and inclusion are created. Sports and play break down the traditional barriers that keep people apart by opening hearts and minds, and changing behaviors through shared, meaningful acts of sportsmanship, accomplishment, community and friendship.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 24,
        title: "The Perfect Summer Shred Workouts and Cardio",
        author: "Cellucor",
        category: 'Health & Fitness',
        price: 1500,
        oldPrice: 2000,
        discount: '-25%',
        rating: 4.4,
        reviews: 98,
        format: 'PDF',
        pages: 7,
        pdfUrl: "https://drive.google.com/file/d/1-Z9rF7fGgyhJf6twdrJd4EgpGwldb1nq/view?usp=sharing",
        driveFileId: "1-Z9rF7fGgyhJf6twdrJd4EgpGwldb1nq",
        embedUrl: "https://drive.google.com/file/d/1-Z9rF7fGgyhJf6twdrJd4EgpGwldb1nq/preview",
        description: "If you're looking to burn down the old you on a tight deadline this summer, then send those old straight-set workouts packing! To get ultra-ripped, you need to amp up your overall training intensity. In this program, that means supersets, dropsets, clusters, and density training. Stick with this program for at least 4 weeks to give it the best chance to work. Along with the nutrition and supplementation guidelines, it should be enough to kick-start some serious progress.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 25,
        title: "Active Learning",
        author: "Cynthia J Brame",
        category: 'Education',
        price: 1400,
        oldPrice: 1900,
        discount: '-26%',
        rating: 4.5,
        reviews: 53,
        format: 'PDF',
        pages: 6,
        pdfUrl: "https://drive.google.com/file/d/1N-r3hPVRA9HSDkdKRJ6eLVGoZCI-B_MR/view?usp=sharing",
        driveFileId: "1N-r3hPVRA9HSDkdKRJ6eLVGoZCI-B_MR",
        embedUrl: "https://drive.google.com/file/d/1N-r3hPVRA9HSDkdKRJ6eLVGoZCI-B_MR/preview",
        description: "Active learning approaches often embrace the use of cooperative learning groups, a constructivist-based practice that places particular emphasis on the contribution that social interaction can make. Lev Vygotsky's work elucidated the relationship between cognitive processes and social activities and led to the sociocultural theory of development, which suggests that learning takes place when students solve problems beyond their current developmental level with the support of their instructor or their peers.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 26,
        title: "Discovering Discovery Learning",
        author: "Kendall Brown & Dr Santarone",
        category: 'Education',
        price: 2800,
        oldPrice: 3700,
        discount: '-24%',
        rating: 4.3,
        reviews: 41,
        format: 'PDF',
        pages: 31,
        pdfUrl: "https://drive.google.com/file/d/16rQxSvWpCneVaYbJX7gK-Zp4lPV-pGE5/view?usp=sharing",
        driveFileId: "16rQxSvWpCneVaYbJX7gK-Zp4lPV-pGE5",
        embedUrl: "https://drive.google.com/file/d/16rQxSvWpCneVaYbJX7gK-Zp4lPV-pGE5/preview",
        description: "Education is in the midst of great change. The role of the teacher, the common core, and the way the content is being taught to students are just a few examples of areas that are undergoing this change. Specifically, the concept of discovery learning is making its way to the classroom. This study explores the effect that discovery learning can have on students, examining how the typical role of a teacher shifts and how cognitive demand increases for students as they become more central to the learning process.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 27,
        title: "Bodycraft Home Gym Guide",
        author: "Bodycraft",
        category: 'Health & Fitness',
        price: 5500,
        oldPrice: 7200,
        discount: '-24%',
        rating: 4.4,
        reviews: 76,
        format: 'PDF',
        pages: 65,
        pdfUrl: "https://drive.google.com/file/d/1hKVTBzn-QNjET3fuAWKyTmWo-AEigyyV/view?usp=sharing",
        driveFileId: "1hKVTBzn-QNjET3fuAWKyTmWo-AEigyyV",
        embedUrl: "https://drive.google.com/file/d/1hKVTBzn-QNjET3fuAWKyTmWo-AEigyyV/preview",
        description: "Before beginning this, or any exercise program, consult your physician. This is especially important for persons over the age of 35, or with preexisting health problems. You may have a preexisting health problem of which you are unaware. This comprehensive guide provides detailed instructions for maximizing your home gym experience and achieving your fitness goals safely and effectively.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 28,
        title: "The Ultimate Guide to Building Muscle Workouts and Recipes",
        author: "Cellucor",
        category: 'Health & Fitness',
        price: 6800,
        oldPrice: 8900,
        discount: '-24%',
        rating: 4.6,
        reviews: 134,
        format: 'PDF',
        pages: 72,
        pdfUrl: "https://drive.google.com/file/d/1Ce8yDqpEZtg2NONaDUmtoVzbtd10t8jN/view?usp=sharing",
        driveFileId: "1Ce8yDqpEZtg2NONaDUmtoVzbtd10t8jN",
        embedUrl: "https://drive.google.com/file/d/1Ce8yDqpEZtg2NONaDUmtoVzbtd10t8jN/preview",
        description: "These eight workouts can be combined in numerous ways, allowing you to create a personalized training split that works for your schedule and goals. Senior content editor Bill Geiger recommends these splits for elite muscle growth. This comprehensive guide includes workout routines, nutrition strategies, and recipes designed to maximize your muscle-building potential.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 29,
        title: "Psychology of Learning",
        author: "University of Mumbai",
        category: 'Psychology',
        price: 12500,
        oldPrice: 16500,
        discount: '-24%',
        rating: 4.5,
        reviews: 89,
        format: 'PDF',
        pages: 164,
        pdfUrl: "https://drive.google.com/file/d/1Nk3edJUpW5QLYF1_jgRCpXMKkd3MN0c8/view?usp=sharing",
        driveFileId: "1Nk3edJUpW5QLYF1_jgRCpXMKkd3MN0c8",
        embedUrl: "https://drive.google.com/file/d/1Nk3edJUpW5QLYF1_jgRCpXMKkd3MN0c8/preview",
        description: "This area is concerned with fundamental questions about learning: How do children acquire skills? When is learning more effective? What are the factors that help the learning process? How do we measure the amount of learning? The study of educational psychology has brought about change in approach, leading to child-centered education. Psychological principles are used in curriculum formulation for different stages, with attempts to provide subjects and activities that conform with student needs, developmental characteristics, learning patterns, and societal needs.",
        sellerId: 'PUzzQ8vdAQaXMYdrm6oKiKElGJJ2',
        sellerName: 'LAN Library',
        sellerEmail: 'lanlibrarydocs@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
];



export const getBooksByCategory = (categorySlug) => {
    return booksData.filter(book => {
        const bookCategory = book.category?.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-');
        return bookCategory === categorySlug;
    });
};

export const getBookById = (bookId) => {
    return booksData.find(book =>
        book.id === bookId ||
        book.id === parseInt(bookId) ||
        book.id === String(bookId)
    );
};

export const bookExists = (bookId) => {
    return getBookById(bookId) !== undefined;
};

export const getAllCategories = () => {
    return [
        'Education',
        'Personal Development',
        'Business',
        'Technology',
        'Science',
        'Literature',
        'Health & Wellness',
        'History',
        'Arts & Culture',
        'Relationship',
        'Self-Help',
        'Finance',
        'Marketing',
        'Programming',
        'Psychology',
        'Fiction',
        'Non-Fiction',
        'Philosophy',
        'Travel',
        'Cooking',
        'Religion & Spirituality',
        'Sex education',
    ];
};