// lib/booksData.js

// Platform Owner Details
export const PLATFORM_OWNER = {
    sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
    sellerName: 'Brown C Emmanuel',
    sellerEmail: 'chigozirimv35@gmail.com',
    sellerPhone: '07013725529',
    accountType: 'platform_owner'
};

export const booksData = [
    {
        id: 38,
        title: "Sexuality is Invented",
        author: "Brown Oziomachi",
        category: 'Sex Education',
        price: 3500,
        oldPrice: 5000,
        discount: '-30%',
        rating: 4.5,
        reviews: 45,
        format: 'PDF',
        pages: 7,
        pdfUrl: "https://drive.google.com/file/d/1itrjVIaT--5P1ucZL_lBE1nJFErLx-pC/view",
        driveFileId: "1itrjVIaT--5P1ucZL_lBE1nJFErLx-pC",
        embedUrl: "https://drive.google.com/file/d/1itrjVIaT--5P1ucZL_lBE1nJFErLx-pC/preview",
        description: 'When you were a child, what reproductive organ someone had did not matter to you but the moment hormones started playing within you, you cannot think of the outside world. There is nothing strange about it, it is just that your hormones have hijacked your intelligence. Your whole intelligence has been completely hijacked by your hormones. You must understand that Sex is a change that happens with adolescence, and is a simple drive within us. Hormones are the drivers of human reproduction, responsible for sexual development and controlling of menstrual cycle.',
        sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
        sellerName: 'Brown C Emmanuel',
        sellerEmail: 'chigozirimv35@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 39,
        title: "On Generation and Corruption",
        author: "Aristotle",
        category: 'Philosophy',
        price: 4500,
        oldPrice: 6500,
        discount: '-31%',
        rating: 4.8,
        reviews: 156,
        format: 'PDF',
        pages: 55,
        pdfUrl: "https://drive.google.com/file/d/1oY66eDT_drRDCnCYjzm8V6DCWrG2duwg/view",
        driveFileId: "1oY66eDT_drRDCnCYjzm8V6DCWrG2duwg",
        embedUrl: "https://drive.google.com/file/d/1oY66eDT_drRDCnCYjzm8V6DCWrG2duwg/preview",
        description: 'Now that we have established the preceding distinctions, we must first consider whether there is anything which comes-to-be and passes-away in the unqualified sense: or whether nothing comes-to-be in this strict sense, but everything always comes-to-be something and out of something- I mean, e.g. comes-to-be-healthy out of being-ill and ill out of being-healthy, comes-to-be-small out of being-big and big out of being-small, and so on in every other instance.',
        sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
        sellerName: 'Brown C Emmanuel',
        sellerEmail: 'chigozirimv35@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 40,
        title: "The Social Contract or Principles of Political Right",
        author: "Jean Jacques Rousseau",
        category: 'Philosophy',
        price: 5000,
        oldPrice: 7000,
        discount: '-29%',
        rating: 4.9,
        reviews: 234,
        format: 'PDF',
        pages: 66,
        pdfUrl: "https://drive.google.com/file/d/1KrvCyjf7wssPZ-tr5JX-UZBxnH7GaG36/view",
        driveFileId: "1KrvCyjf7wssPZ-tr5JX-UZBxnH7GaG36",
        embedUrl: "https://drive.google.com/file/d/1KrvCyjf7wssPZ-tr5JX-UZBxnH7GaG36/preview",
        description: 'MAN is born free; and everywhere he is in chains. One thinks himself the master of others, and still remains a greater slave than they. How did this change come about? I do not know. What can make it legitimate? That question I think I can answer. If I took into account only force, and the effects derived from it, I should say: "As long as a people is compelled to obey, and obeys, it does well; as soon as it can shake off the yoke, and shakes it off, it does still better; for, regaining its liberty by the same right as took it away, either it is justified in resuming it, or there was no justification for those who took it away." But the social order is a sacred right which is the basis of all other rights.',
        sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
        sellerName: 'Brown C Emmanuel',
        sellerEmail: 'chigozirimv35@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 41,
        title: "Facilitating Effective Teaching through Learning Styles and Thinking",
        author: "Siti Aisyah Ginting",
        category: 'Education',
        price: 3000,
        oldPrice: 4500,
        discount: '-33%',
        rating: 4.6,
        reviews: 78,
        format: 'PDF',
        pages: 9,
        pdfUrl: "https://drive.google.com/file/d/1Q_ZPJPy0uSdeYTiTmjcPmzF7Yk7bskki/view",
        driveFileId: "1Q_ZPJPy0uSdeYTiTmjcPmzF7Yk7bskki",
        embedUrl: "https://drive.google.com/file/d/1Q_ZPJPy0uSdeYTiTmjcPmzF7Yk7bskki/preview",
        description: 'The study deals with learning styles and ways of thinking in facilitating effective teaching. The objective of this study was to investigate the relationship between students\' learning style and ways of thinking toward effective teaching. This study was conducted by using correlational design. The population of the study were 360 university students of English education academic year 2015/2016 in State University of Medan. The samples were 82 university students selected by using random sampling. The data were collected by using questionnaires and tests.',
        sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
        sellerName: 'Brown C Emmanuel',
        sellerEmail: 'chigozirimv35@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 42,
        title: "Classical Political Philosophy and Modern Democracy",
        author: "Rebekkah Brainerd",
        category: 'Philosophy',
        price: 3500,
        oldPrice: 5000,
        discount: '-30%',
        rating: 4.7,
        reviews: 92,
        format: 'PDF',
        pages: 9,
        pdfUrl: "https://drive.google.com/file/d/17NwvgJbBK4g_bhD8IRz8tweT-i28bR8k/view",
        driveFileId: "17NwvgJbBK4g_bhD8IRz8tweT-i28bR8k",
        embedUrl: "https://drive.google.com/file/d/17NwvgJbBK4g_bhD8IRz8tweT-i28bR8k/preview",
        description: 'This paper will be looking at the classical political theories of Plato, Aristotle and Thucydides on democracy to prove they are still relevant and applicable, as well as looking into the problem of democratic corruption.',
        sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
        sellerName: 'Brown C Emmanuel',
        sellerEmail: 'chigozirimv35@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 43,
        title: "What is Collaborative Learning",
        author: "Barbara Leigh Smith, Jean T MacGregor",
        category: 'Education',
        price: 5500,
        oldPrice: 7500,
        discount: '-27%',
        rating: 4.8,
        reviews: 167,
        format: 'PDF',
        pages: 97,
        pdfUrl: "https://drive.google.com/file/d/1dPnqYn_B3RRhnZSwWmQwPim4XAAo_jVl/view",
        driveFileId: "1dPnqYn_B3RRhnZSwWmQwPim4XAAo_jVl",
        embedUrl: "https://drive.google.com/file/d/1dPnqYn_B3RRhnZSwWmQwPim4XAAo_jVl/preview",
        description: 'Collaborative learning is particularly timely now. In the 1980\'s an avalanche of reports underscored the problems of undergraduate education: the distance between faculty and students, the fragmentation of the curriculum, a prevailing pedagogy of lecture and routinized tests, an educational culture that reinforces student passivity, high rates of student attrition, and a reward system that gives low priority to teaching. Collaborative learning, with its emphasis on social and intellectual engagement and mutual responsibility, aims to counteract many of these educational and societal trends.',
        sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
        sellerName: 'Brown C Emmanuel',
        sellerEmail: 'chigozirimv35@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 44,
        title: "Associative Learning and Behaviour: An Algebraic Approach to Symmetries",
        author: "Eduardo Alonso, Esther Mondragon",
        category: 'Psychology',
        price: 4000,
        oldPrice: 6000,
        discount: '-33%',
        rating: 4.7,
        reviews: 103,
        format: 'PDF',
        pages: 27,
        pdfUrl: "https://drive.google.com/file/d/1ndTMkrcfHeoqkZVfzpQz2-WheDg89fkI/view",
        driveFileId: "1ndTMkrcfHeoqkZVfzpQz2-WheDg89fkI",
        embedUrl: "https://drive.google.com/file/d/1ndTMkrcfHeoqkZVfzpQz2-WheDg89fkI/preview",
        description: 'The ability of animals to recognise and adapt to patterns of stimuli and to form causal links in dynamic environments is essential for their survival. Associative learning studies how animals learn (that is, how they acquire information) and behave (that is, how what has been learned is expressed in their behaviour) and is, therefore, of paramount importance in Psychology. Models of associative learning have proved to be relevant to human learning both theoretically and in practice in such diverse areas as behavioural therapy, drug addiction rehabilitation, or anticipatory nausea in cancer treatment.',
        sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
        sellerName: 'Brown C Emmanuel',
        sellerEmail: 'chigozirimv35@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 45,
        title: "Types of Learning",
        author: "Maike Looß",
        category: 'Education',
        price: 4500,
        oldPrice: 6500,
        discount: '-31%',
        rating: 4.6,
        reviews: 124,
        format: 'PDF',
        pages: 40,
        pdfUrl: "https://drive.google.com/file/d/1Xytbaw6wmWRirlDn1de1pNfVP2c4wI2U/view",
        driveFileId: "1Xytbaw6wmWRirlDn1de1pNfVP2c4wI2U",
        embedUrl: "https://drive.google.com/file/d/1Xytbaw6wmWRirlDn1de1pNfVP2c4wI2U/preview",
        description: 'Learning type 1: auditive learning (by listening and speaking), Learning type 2: visual learning (through the eyes, by watching), Learning type 3: haptic learning (by touching and feeling), Learning type 4: learning through the intellect. This kind of classification calls for a critical analysis. Learning type 1 to 3 differ in the kind of receptive channel (sensory mode) for an information. Logically the fourth type of learning does not fit into this category.',
        sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
        sellerName: 'Brown C Emmanuel',
        sellerEmail: 'chigozirimv35@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 46,
        title: "Learners and the Learning Process",
        author: "Ismail Thamarasseri",
        category: 'Education',
        price: 3000,
        oldPrice: 4500,
        discount: '-33%',
        rating: 4.5,
        reviews: 87,
        format: 'PDF',
        pages: 9,
        pdfUrl: "https://drive.google.com/file/d/1lqf68yJc1yb7BB_XheIK65T-yUc0y3jS/view",
        driveFileId: "1lqf68yJc1yb7BB_XheIK65T-yUc0y3jS",
        embedUrl: "https://drive.google.com/file/d/1lqf68yJc1yb7BB_XheIK65T-yUc0y3jS/preview",
        description: 'For a long period our system of education especially school education centred on teacher. Now there is change. The Learner came to limelight. The learner plays a pivotal role in the education process. There are five dispositions that the learner should have to help them become active and autonomous learners: be inquisitive, take initiative, be confident, be inventive, and be reflective. First, the learner should be inquisitive. An inquisitive learner is one that asks many questions and wants to find out new information and will investigate.',
        sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
        sellerName: 'Brown C Emmanuel',
        sellerEmail: 'chigozirimv35@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    },
    {
        id: 47,
        title: "The Effect of Discovery Learning Method Application",
        author: "Education Resources Information Center",
        category: 'Education',
        price: 3500,
        oldPrice: 5000,
        discount: '-30%',
        rating: 4.6,
        reviews: 95,
        format: 'PDF',
        pages: 16,
        pdfUrl: "https://drive.google.com/file/d/1UPXcNHvhrjv4Zac_Acg-fvk5UZnFYIHH/view",
        driveFileId: "1UPXcNHvhrjv4Zac_Acg-fvk5UZnFYIHH",
        embedUrl: "https://drive.google.com/file/d/1UPXcNHvhrjv4Zac_Acg-fvk5UZnFYIHH/preview",
        description: 'Discovery Learning is a learning method that encourages students to ask questions and formulate their own tentative answers, and to deduce general principles from practical examples or experiences. Other definition states that Discovery Learning is a learning situation in which the principal content of what is to be learned is not given but must be independently discovered by the student.',
        sellerId: 'yrylYEHv18PVghDWl8IoWzmlhpS2',
        sellerName: 'Brown C Emmanuel',
        sellerEmail: 'chigozirimv35@gmail.com',
        sellerPhone: '07013725529',
        source: 'platform',
        isPlatformBook: true,
    }
];

export const getBooksByCategory = (categorySlug) => {
    return booksData.filter(book => {
        const bookCategory = book.category?.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-');
        return bookCategory === categorySlug;
    });
};

export const getBookById = (bookId) => {
    return booksData.find(book =>
        book.id === bookId ||
        book.id === parseInt(bookId) ||
        book.id === String(bookId)
    );
};

export const bookExists = (bookId) => {
    return getBookById(bookId) !== undefined;
};

export const getAllCategories = () => {
    return [
        'Education',
        'Personal Development',
        'Business',
        'Technology',
        'Science',
        'Literature',
        'Health & Wellness',
        'History',
        'Arts & Culture',
        'Relationship',
        'Self-Help',
        'Finance',
        'Marketing',
        'Programming',
        'Psychology',
        'Fiction',
        'Non-Fiction',
        'Philosophy',
        'Travel',
        'Cooking',
        'Religion & Spirituality',
        'Sex education',
    ];
};